name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-camunda-7:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    - name: Build
      run: mvn verify -PcheckFormat -B
      working-directory: process-solution-camunda-7
  build-camunda-8:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    - name: Build
      run: mvn verify -PcheckFormat -B
      working-directory: process-solution-camunda-8